import type { Metadata } from 'next'
import { Outfit } from 'next/font/google'
import './globals.css'
import Header from './_components/Header'
// import Footer from './_components/Footer'
import { ClerkProvider } from '@clerk/nextjs'
import { Toaster } from '@/components/ui/sonner'
import { SpeedInsights } from '@vercel/speed-insights/next';
const outfit = Outfit({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={outfit.className}>
          <div className="md:px-20">
            <Header />
            {children}
            <SpeedInsights />
            <Toaster />
          </div>
          {/* <Footer /> */}
        </body>
      </html>
    </ClerkProvider>
  )
}
